baseURL = "/"
title = "Refuleras"
languageCode = "es-es"
defaultContentLanguage = "es"
paginate = "2"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Refuleras" # title for frontpage, may include image
copyright = ""
description = '<img src="{{ "img/test.svg" | absURL }}" alt=""> Red de Colectivas <br />Futboleras Feministas<br /> '
startbuttonText = "Cuestionario"
startbuttonLink = "https://refuleras.limesurvey.net/212382?lang=es"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
images = ["/images/banner.jpg"]

[[params.menu.main]]
url = '/'
title = "Proyecto"

[[params.menu.main]]
url = '/post/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Quiénes somos <br/> R E F U L E R A S'
body = '''
Somos una red de mujeres y disidencias del fútbol integrada por:<br/>


Guinda! | En la Cancha | Futbolistas de Uruguay | <br/>Mujeres periodistas | 
Bohemias feministas | Hinchas de Danubio en resistencia | <br/>Mujeres hinchas de Defensor | Hinchas de Peñarol<br/> '''


[params.two]
enable = true

[[params.two.section]]
img = "images/refuleras_letras.png"
img_alt = "Red de Colectivas Futboleras Feministas"
title = 'Misión'
body = 'Militamos desde los feminismos por la posibilidad de otro fútbol posible. El objetivo de esta red es trabajar de manera colectiva en pos de la disminución de las desigualdades basadas en género en el fútbol y la erradicación de las violencias basadas en género en dicho ámbito. Nos comprometemos a sostener un espacio de participación de mujeres y disidencias en el fútbol desde dónde tejer, construir fuerza colectiva para ir acompañando año a año distintas luchas.'

[[params.two.section]]
img = "images/refuleras_abrazo.png"
title = 'Visión'
body = 'Buscamos visibilizar la brecha de género existente en el fútbol. Apostamos a transformar las inequidades por razones de género en el fútbol: en el acceso -en cantidad y calidad- y en la participación de las mujeres y disidencias en el deporte. Brechas que solo puedan acortarse/desparecer si, conjuntamente con otras acciones, logramos erradicar la discriminación y la violencia explícita y simbólica que vivimos día a día habitando estos espacios que nos pertenecen pero al mismo tiempo no.'

[[params.two.section]]
img = "images/hito.jpg"
title = 'Historia'
body = 'Surgimos en febrero de 2022 gracias al interés por parte de diversos espacios de militancia futbolera de marchar en bloque el 8M en Montevideo. Marchar para reivindicar a las mujeres y disidencias del fútbol, para decir acá estamos; siempre estuvimos. Esta Red se fue ampliando y hoy se compone de espacios de práctica de fútbol que buscan brindar entornos cuidados de aprendizaje y entrenamiento para mujeres y disidencias, reivindicando el derecho al goce y el juego por parte de todes; agrupaciones de hinchas que se proponen romper con los mandatos del fútbol hegemónico -el heteromasculinizado- a la vez que revisan sus propias trayectorias en las tribunas y en las canchas y (re)construyen formas de habitar este deporte; un grupo de periodistas y comunicadoras que trabajan por los abordajes de las temáticas del deporte desde una perspectiva feminista.'

[[params.two.section]]
img = "images/exterior.jpg"
title = 'Sumate!<br />Queremos ser más.'
body = 'Si sos parte de una organización relacionada al fútbol o te interesa sumarte a nuestra red envianos un mensaje a @refulerasuy o un mail a contacto@refuleras.org'

[params.three]
enable = true
title = 'P r o y e c t o<br />Mujeres y Disidencias del Fútbol: <br />juntas en la cancha y en las calles'
body = '''
En 2024, Refuleras se presentó a la convocatoria de proyectos del 
<a href="https://www.mujeresdelsur.org/">Fondo Mujeres del Sur</a>  (<https://www.mujeresdelsur.org/>), con la propuesta Mujeres y Disidencias del Fútbol: juntas en la cancha y en las calles, la cual fue aprobada para su desarrollo hasta julio de 2025. 
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Objetivo"
body = "A través de esta iniciativa buscamos el fortalecimiento de las colectivas que integran la red y la realización de un relevamiento de datos sobre mujeres y disidencias que practican fútbol."

[[params.three.feature]]
icon = "solid fa-futbol"
title = "Fútbol"
body = "Nos interesa relevar información de quiénes practican fútbol en sus distintas modalidades -calle, picado, fútbol 5, fútbol sala, fútbol 11, fútbol 7, fútbol playa- y niveles -federado, no federado y comunitario. "

[[params.three.feature]]
icon = "solid fa-comment"
title = "Participantes"
body = "En esta primera etapa, el relevamiento está dirigido a mujeres y disidencias de 14 años o más, que vivan en Montevideo o el Área Metropolitana y hayan jugado al fútbol alguna vez en los últimos dos años. "

[[params.three.feature]]
icon = "fa-check-square"
title = "Cuestionario"
body = "El objetivo del cuestionario es relevar información sobre los espacios que existen para la práctica del fútbol para mujeres y disidencias. Cómo habitan esos espacios y qué cosas se deben mejorar. "

[[params.three.feature]]
icon = "solid fa-bar-chart"
title = "Resultados"
body = "Una vez concluido el relevamiento, a mediados de 2025, vamos a difundir y publicar los resultados y hacerlos llegar a quienes toman decisiones en el ámbito público y privado.  Es nuestra aspiración que los resultados puedan ser utilizados como insumo para visibilizar de una manera amigable la situación de las mujeres y disidencias en el fútbol para que podamos cambiar positivamente la realidad."

[[params.three.feature]]
icon = "fa-heart"
title = "Compartir"
body = "Si este proyecto te resultó interesante, te agradecemos les pases el link de esta página o nuestro instagram a otras personas que conozcas y creas que les puede interesar. Si tenés dudas si completar o no el cuestionario, completalo."


[params.cta]
enable = true
title = "Compartir"
body = "Si este proyecto te resultó interesante, te agradecemos les pases el link de esta página o nuestro Instagram a otras personas que conozcas y creas que les puede interesar."

[[params.cta.link]]
href = "#"
text = "Cuestionario"
special = true

[[params.cta.link]]
href = "#"
text = "Conocenos"
special = false

[params.contact]
enable = true
title = "Contacto"
body = "Dejanos un mensaje"
phone = ""
address = "Montevideo<br />Uruguay"
email = "contacto@refuleras.org"
subject = "Mensaje"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = "refulerasuy"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.es]
weight = 10
languageName = "Español"
