---
title: "Líneas de ayuda"
author: ""
date: "2024-10-01"
categories: ["recursos"]
tags: ["violencia", "consumo", "salud mental"]
---

## Salud Mental

**Para que ya no haya #NiSilencioNiTabú, hablemos de salud mental.**

Si vos o alguien que conozcas necesita ayuda, existen líneas de apoyo que son gratuitas y atienden las 24 horas.

- Línea de **apoyo emocional**, llamando al **0800 1920**. 
- Línea de **prevención del suicidio**, llamando al **0800 0767** o por celular \*0767.
- **Espacio Contás de la Intendencia de Montevideo**: Es un espacio gratuito dirigido a jóvenes de entre 15 a 20 años que residan en Montevideo. Agenda por correo al contas@imm.gub.uy o enviando la palabra "Chatear" al Whatsapp 099 019 500 y seleccionando la opción "Contás". Por más información visitar: <https://montevideo.gub.uy/espacio-contas>
- Próximamente 7 **Centros Ni Silencio Ni Tabú**: Los Centros de promoción y atención del programa Ni Silencio Ni Tabú - impulsado por el Ministerio de Desarrollo Social, a través de INJU junto a UNICEF y con el apoyo del Ministerio de Salud Pública - comenzarán a funcionar en el segundo semestre de 2024 en Montevideo, Cerro Largo, Rocha (en funcionamiento), Florida, Río Negro y Canelones. 

Conocé, compartí, informate más en:
<https://www.gub.uy/salud-mental-adolescente/programa/centros-de-promocion-del-bienestar-psicoemocional-de-adolescentes>

## Violencia

Si tu o alguien que tu conocés está atravesando alguna situación de violencia, abuso o maltrato, podés pedir ayuda, información o denunciar acá: 

- **0800 5050** (desde teléfono fijo) y \*5050 (desde celular): Recepción de **denuncias de situaciones de todo tipo de maltrato**, ya sea físico, psicológico, abuso sexual, explotación u otras forma de vulneración de derechos hacia niños, niñas y adolescentes.
- **0800 5000** (desde teléfono fijo) y \*5000 (desde celular): recepción de **denuncias anónimas**.
- **0800 4141** (desde teléfono fijo) y \*4141 (desde celular): Servicio telefónico de **orientación a mujeres en situación de Violencia Doméstica**. Gratuito, confidencial, de alcance nacional que funciona los 365 días del año.
- 911: ante **situaciones de urgencia o riesgo de vida** es importante: Recuerde que si reside en el interior deberá marcar el 4 + la característica del departamento + 911.

## Consumo problemático de drogas

Si tú o alguien que conocés está atravesando alguna situación de consumo problemático de drogas y necesita ayuda, puedes comunicarte las 24 hs y de forma gratuita a la siguiente línea telefónica:

- Servicio de información, apoyo, contención y asesoramiento en casos de uso problemático de drogas: \*1020 desde celular; **2309102** desde un teléfono fijo.

Por más información: <https://www.gub.uy/junta-nacional-drogas/>
